### ISSUE TITLE
CIVET preprocessing error: export: BASH_FUNC_module%%: bad variable name

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/documentation#1]
Hi,

I get the following error message when I'm trying to run the CIVET preprocessing pipeline:

/var/spool/gridengine/execd/cajal/job_scripts/223574: 33: export: BASH_FUNC_module%%: bad variable name

This is in the 'logs' folder of a subject. Most subjects don't have a '.log' file and the ones that do, have the error message right after the "Available SubCommands and Args" listing. 

This is where all the files are stored: /projects/saba/RTMSWM/civet/

Thanks!!

**Comment by pipitone** [comment]
Does CIVET continue to run? 

I think this might be a known bug with the modules system. Something similar to this: 

https://github.com/TIGRLab/admin/issues/178#issuecomment-77392434

If it's causing problems with CIVET actually running, that's a different matter...

**Comment by sabashahab** [comment]
The process didn't terminate on the terminal and it showed as 'Eqw' in the queue. And unlike Melissa's earlier post above, all subfolders were empty. 

Entering this on the terminal gave a better error message. It was a "can't open directory" issue: qstat -j jobid | grep error

I changed the permissions of the subject folders in the output folder and now the preprocessing is running.

PS: I was checking my CIVET preprocessing output for another data set and VBM failed (similar to Melissa's post). I don't need it but thought I should let you know about it.

**Comment by pipitone** [comment]
This issue was moved to TIGRLab/admin#241
