### ISSUE TITLE
incomplete/missing nhdr files for 1.5T data in the /archive/data folder

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/documentation#2]
I am running DTIPrep and UKFTractography on some of the 1.5 T data. I am having trouble running it on some of the subjects for the following reasons: 

In /archive/data/DT_sample/Schizophrenics/allDTI:
1. Some subject folders don't contain an nhdr/raw.gz file e.g.: S054, S146, S147. How do I get the nrrd format files for these subjects?
2. Some subjects do have nhdr/raw.gz files but their nhdr files don't have gradient information. e.g.: S137, S148. Why are these nhdr files missing this information? And what do I need to do to get the complete nhdr files for these subjects?

**Comment by pipitone** [comment]
Two things: this isn't the right repository to file data issues. In the future put issues here: http://github.com/tigrlab/admin

Also, the 1.5T data is still a mess. Navona and Erin have been going through the original data to get it organized and have much of it done. Once that is finished (or starting now with just the subjects we are 100% sure of) we can reexport the raw data to nrrd.
