### ISSUE TITLE
How do I set up a Paperpile account?

### ISSUE THREAD

**Issue by josephmje** [TIGRLab/documentation#3]

**Comment by gabiherman** [comment]
1. Click "sign in" on the main paperpile website: 
![image](https://user-images.githubusercontent.com/39273726/44920933-2c0d8b80-ad0f-11e8-8951-3747bff7c377.png)

2. Sign in with your google account, and give paperpile the permissions it requests. Optionally, install the Google Chrome paperpile extension (Erin says it's very good). 

3. You should be taken to a homepage that looks like this: 
![image](https://user-images.githubusercontent.com/39273726/44921111-a3431f80-ad0f-11e8-9b2c-1b72cff1382d.png)

4. Mouse over the gear in the top right corner and click settings. 

5. Under settings --> account, there should be an "activate site license" button. (Click it.): 

![image](https://user-images.githubusercontent.com/39273726/44921172-cec60a00-ad0f-11e8-864e-ced2a19a11ca.png)

6. Enter your CAMH email and click "Check now"

![image](https://user-images.githubusercontent.com/39273726/44921207-e3a29d80-ad0f-11e8-8910-527c367e7dfe.png)


7. Hooray! 

![image](https://user-images.githubusercontent.com/39273726/44921246-05038980-ad10-11e8-802c-790395bd8668.png)
